apiVersion: v1
name: mysql
version: 1.6.4 
appVersion: 5.7.30
description:
keywords:
- mysql
- database
- sql
home: https://mydomain.com/
sources: 
- https://github.com/kubernetes/charts
- https://github.com/docker-library/mysql
maintainers: []
engine: gotpl
